
export const ariaAttributes: string[] = [
  'aria-activedescendant',
  'aria-atomic',
  'aria-autocomplete',
  'aria-busy',
  'aria-checked',
  'aria-colcount',
  'aria-colindex',
  'aria-colspan',
  'aria-controls',
  'aria-current',
  'aria-describedby',
  'aria-details',
  'aria-disabled',
  'aria-dropeffect',
  'aria-errormessage',
  'aria-expanded',
  'aria-flowto',
  'aria-grabbed',
  'aria-haspopup',
  'aria-hidden',
  'aria-invalid',
  'aria-keyshortcuts',
  'aria-label',
  'aria-labelledby',
  'aria-level',
  'aria-live',
  'aria-modal',
  'aria-multiline',
  'aria-multiselectable',
  'aria-orientation',
  'aria-owns',
  'aria-placeholder',
  'aria-posinset',
  'aria-pressed',
  'aria-readonly',
  'aria-relevant',
  'aria-required',
  'aria-roledescription',
  'aria-rowcount',
  'aria-rowindex',
  'aria-rowspan',
  'aria-selected',
  'aria-setsize',
  'aria-sort',
  'aria-valuemax',
  'aria-valuemin',
  'aria-valuenow',
  'aria-valuetext',
  'role'
]

export const standardAttributes: string[] = [
  // Global attributes
  'accesskey',
  'autocapitalize',
  'autofocus',
  'class',
  'contenteditable',
  'contextmenu',
  'dir',
  'draggable',
  'enterkeyhint',
  'hidden',
  'http-equiv',
  'id',
  'inputmode',
  'is',
  'itemid',
  'itemprop',
  'itemref',
  'itemscope',
  'itemtype',
  'lang',
  'nonce',
  'part',
  'slot',
  'spellcheck',
  'style',
  'tabindex',
  'title',
  'translate',

  // Form-related
  'accept',
  'accept-charset',
  'action',
  'autocomplete',
  'checked',
  'cols',
  'disabled',
  'enctype',
  'for',
  'form',
  'formaction',
  'formenctype',
  'formmethod',
  'formnovalidate',
  'formtarget',
  'list',
  'max',
  'maxlength',
  'method',
  'min',
  'minlength',
  'multiple',
  'name',
  'novalidate',
  'pattern',
  'placeholder',
  'readonly',
  'required',
  'rows',
  'selected',
  'size',
  'step',
  'type',
  'value',

  // Media-related
  'alt',
  'autoplay',
  'controls',
  'crossorigin',
  'height',
  'loop',
  'muted',
  'playsinline',
  'poster',
  'preload',
  'sizes',
  'src',
  'srcset',
  'width',

  // Link/Meta-related
  'charset',
  'content',
  'download',
  'href',
  'hreflang',
  'media',
  'rel',
  'target',
  'type',

  // Table-related
  'colspan',
  'headers',
  'rowspan',
  'scope',

  // Script-related
  'async',
  'defer',
  'integrity',
  'nomodule',
  'referrerpolicy',
  'src',
  'type'
]

export const vueAttributes: string[] = [
  ...standardAttributes,
  ...ariaAttributes,
  // Vue directives
  'v-bind',
  'v-on',
  'v-if',
  'v-else',
  'v-else-if',
  'v-for',
  'v-model',
  'v-show',
  'v-html',
  'v-text',
  'v-pre',
  'v-once',
  'v-cloak',
  'v-memo',
  'v-slot',
  // Common shorthand syntax
  ':class',
  ':style',
  ':key',
  ':is',
  '@click',
  '@input',
  '@change',
  '@submit',
  '@keyup',
  '@keydown',
  '@focus',
  '@blur',
  // Slot related
  '#default',
  '#named'
]

export const angularAttributes: string[] = [
  ...standardAttributes,
  ...ariaAttributes,
  // Structural directives
  '*ngIf',
  '*ngFor',
  '*ngSwitch',
  '*ngSwitchCase',
  '*ngSwitchDefault',
  // Property bindings
  '[class]',
  '[style]',
  '[attr]',
  '[id]',
  '[hidden]',
  // Event bindings
  '(click)',
  '(input)',
  '(change)',
  '(submit)',
  '(keyup)',
  '(keydown)',
  '(focus)',
  '(blur)',
  // Two-way binding
  '[(ngModel)]',
  // Template reference variables
  '#templateRef',
  // Other common directives
  'ngClass',
  'ngStyle',
  'ngTemplateOutlet',
  'ngContent'
]

export const reactAttributes: string[] = [
  ...standardAttributes,
  ...ariaAttributes,
  // React-specific attributes
  'defaultValue',
  'defaultChecked',
  'suppressContentEditableWarning',
  'suppressHydrationWarning',
  'dangerouslySetInnerHTML',
  // Event handlers
  'onChange',
  'onClick',
  'onSubmit',
  'onKeyPress',
  'onKeyDown',
  'onKeyUp',
  'onFocus',
  'onBlur',
  'onMouseEnter',
  'onMouseLeave',
  // React ref
  'ref',
  'key'
]

export const fullAttributes: string[] = [
  ...standardAttributes,
  ...ariaAttributes,
  ...vueAttributes.filter(attr => !standardAttributes.includes(attr)),
  ...angularAttributes.filter(attr => !standardAttributes.includes(attr)),
  ...reactAttributes.filter(attr => !standardAttributes.includes(attr))
]

export default {
  standardAttributes,
  ariaAttributes,
  vueAttributes,
  angularAttributes,
  reactAttributes,
  fullAttributes
}
